### PR TITLE
Raport logo will now work offline 🖼️✈️

### PR DESCRIPTION
**Pull request by jankoksik**
Hi!,
it's me again....
I changed logo to be downloaded and parsed into base64 during raport generation so the raport will also work offline 😎
I also added an exception for raport if curl couldnt be generated (i had this issue with testing my localhost)

### CODE REVIEW

**Comment by dolevf** [comment]
Hey,

It will be better to embed the base64 right into the HTML template so it's always just part of the code instead of downloading it I think.

**Comment by jankoksik** [comment]
That's the change :D

**Comment by jankoksik** [comment]
I mean i wnated the logo to be changeable but i can also make ot hardcoded if you want, or make it as a flag. For exaple flag -l / --logo is present the logo will be downloaded istead of hardcoded. What do you think?

**Comment by jankoksik** [comment]
Done 🥳

**Comment by jankoksik** [comment]
I can also move it to seperate file like logo.py so the utils wont look so messy...

**Pull request merged**
